name: Manual Input and Process Workflow
on:
  workflow_dispatch:
    inputs:
      comments:
        description: 'Comments for approval'
        required: false
        default: 'No comments provided'

jobs:
  process-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Check Comments
        run: echo "Received comments: ${{ github.event.inputs.comments }}"
