name: Manual Input and Process Workflow
on:
  workflow_dispatch

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: RUN ascript
        run: |
          echo "dev ${{ vars.DEV_VAR }} "
  QA:
    runs-on: ubuntu-latest
    environment: qa
    needs: DEV
    steps:
      - uses: actions/checkout@v2
      - name: RUN ascript
        run: |
          echo "qa  ${{ vars.QA_VAR }}"
  PROD:
    runs-on: ubuntu-latest
    environment: prod
    needs: QA
    steps:
      - uses: actions/checkout@v2
      - name: RUN ascript
        run: |
          echo "prod ${{ vars.PROD_VAR }}"

