name: Manual Input and Process Workflow
on:
  workflow_dispatch

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: RUN ascript
        run: |
          echo "dev"
  QA:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v2
      - name: RUN ascript
        run: |
          echo "qa"
  PROD:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: RUN ascript
        run: |
          echo "prod"

